spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: ${ACTIVE:dev}

server:
  servlet:
    context-path: /api
